### ISSUE TITLE
Implement the bitmasking algorithm

### ISSUE THREAD

**Issue by PersonligaPersson** [AmandaStromdahl/algorithms#10]
To solve issue #480 in the original repository we must implement the bitmasking algorithm. 

https://www.geeksforgeeks.org/bitmasking-and-dynamic-programming-set-1-count-ways-to-assign-unique-cap-to-every-person/

**Comment by BastienFaivre** [comment]
The algorithm is implemented using two methods, what do you think is better between just writing this two methods in the file or creating a relevant class that contains these two methods ?

**Comment by BastienFaivre** [comment]
As discussed in the today's meeting with the group, we decided to write the two methods without a class since create a class has no sense for this algorithm, and we want to follow the same structure as the other algorithm

**Comment by BastienFaivre** [comment]
This is done
