### ISSUE TITLE
Algorithm proposition

### ISSUE THREAD

**Issue by BastienFaivre** [AmandaStromdahl/algorithms#24]
I found a interesting problem whose the solution uses also bitmasking and DP, this is the **Traveling Salesman Problem**. I think it could be a good addition to the resolution of our issue since it is part of the technique (bitmasking) we're implementing. Here is the link to the problem: https://www.geeksforgeeks.org/bitmasking-dynamic-programming-set-2-tsp/?ref=lbp
The addition of this problem in the group task will mainly include:

- Write the algorithm description
- Implement the algorithm
- Write tests for the algorithm
- Further necessary tasks

Give me your opinion on this proposition. We can also discuss it during the today's meeting.

**Comment by PersonligaPersson** [comment]
I had to write an implementation of TSP for the advanced algorithms course. It would be interesting to to see how well bitmasking as a technique would work on this problem. Let's talk about it during the meeting.

**Comment by mellonnen** [comment]
As decided we are implementing this problem and the required issues (#31 #32 #33) are created this issue can be closed
