### ISSUE TITLE
Fix test cases

### ISSUE THREAD

**Issue by mellonnen** [AmandaStromdahl/algorithms#25]
The initial test cases merged in #9 and the proposed implementation in #21 are not compatible. To keep it simple we should update the test cases to accommodate the implementation

**Comment by BastienFaivre** [comment]
I just saw that there are some warnings when we run the test: `DeprecationWarning: Please use assertEqual instead.`
Should we take this into account ?

**Comment by mellonnen** [comment]
No I think it is fine, the original repo uses assertEquals all the time.

**Comment by mellonnen** [comment]
merged in #10
