### ISSUE TITLE
Create a UML diagram of the code that was added for the issue

### ISSUE THREAD

**Issue by AmandaStromdahl** [AmandaStromdahl/algorithms#3]
Classes, fields, or methods that are not relevant do not need to be included, unless they help with
the overall understanding. Typically, the diagram would contain 5–10 classes.

**Comment by PersonligaPersson** [comment]
Paused this issue until the meeting. What we are working on currently only contains 1 class.

**Comment by PersonligaPersson** [comment]
After discussions the most fitting type of diagram was determined to be a sequence diagram to show the flow of control between the functions in the class.

**Comment by PersonligaPersson** [comment]
Closed in #55
