### ISSUE TITLE
Write an account of the effort spent and prepare links to files for each member

### ISSUE THREAD

**Issue by AmandaStromdahl** [AmandaStromdahl/algorithms#34]
Write an overview of how much time was spent for different tasks and prepare four links to documents where each member can include a complete account of how they spent their time throughout the project.

**Comment by PersonligaPersson** [comment]
Instead of having individual files for each member we decided to add a single linked google sheet for the sake of clarity.

**Comment by PersonligaPersson** [comment]
This was closed in #35
