### ISSUE TITLE
Describe the changes in the Patch section in the report

### ISSUE THREAD

**Issue by BastienFaivre** [AmandaStromdahl/algorithms#49]
Describe the changes in the *Patch* section in the report. See point 3.1.5 in the assignment

**Comment by PersonligaPersson** [comment]
The patch in question is the pull request that will be performed when we have created a clean branch, devoid of any of our personal documentation files. This is not a separate document imo. For this reason I will close this issue. If you wish to reopen it again later we can talk about it.
