### ISSUE TITLE
Create the final PR branch

### ISSUE THREAD

**Issue by BastienFaivre** [AmandaStromdahl/algorithms#53]
Create the branch that will be send as a PR in the original repo

**Comment by BastienFaivre** [comment]
Note: we also have to update the [README](https://github.com/AmandaStromdahl/algorithms/blob/master/README.md) to include our algorithms

**Comment by PersonligaPersson** [comment]
I will create this branch when all other issues are closed.

**Comment by PersonligaPersson** [comment]
Pr branch now ready. Closing.
