### ISSUE TITLE
Create a logger service for tests

### ISSUE THREAD

**Issue by PersonligaPersson** [AmandaStromdahl/algorithms#8]
Point 6 in 3.1 (P) states that "Tests are automated, their outcome is documented, e.g., as a test log." 

Thus we need to write a logging service that dumps the outcome of tests to files.  Try to stick to a limited amount of output files.

**Comment by mellonnen** [comment]
I will look at this

**Comment by mellonnen** [comment]
By automated, do they mean that the tests are run through github actions?
